name: Docker CI to GHCR

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ghcr-build-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - name: default
            file: Dockerfile
            tag: latest
          - name: gpu
            file: Dockerfile.gpu
            tag: gpu
          - name: qwen480b
            file: Dockerfile.qwen480b
            tag: qwen480b
          - name: qwen30b
            file: Dockerfile.qwen30b
            tag: qwen30b-tp1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free disk space on runner (optional)
        run: |
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /opt/hostedtoolcache/CodeQL || true
          sudo rm -rf /opt/hostedtoolcache/go || true
          sudo rm -rf /usr/local/.ghcup || true
          sudo rm -rf /opt/ghc || true
          docker system prune -af || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (${{ matrix.name }})
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.file }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.tag }}
            ghcr.io/${{ github.repository }}:${{ matrix.tag }}-${{ github.sha }}
          provenance: false
          sbom: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Prune builder cache
        run: docker buildx prune -af || true

  smoke-test:
    needs: build-and-push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: latest
            import_cmd: "import runpod, requests, pybase64; print('ok minimal')"
          - tag: gpu
            import_cmd: "import sglang, pybase64; print('ok sglang')"
          - tag: qwen480b
            import_cmd: "import sglang, pybase64; print('ok sglang')"
          - tag: qwen30b-tp1
            import_cmd: "import sglang, pybase64; print('ok sglang')"
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: docker pull ghcr.io/${{ github.repository }}:${{ matrix.tag }}

      - name: Import check
        run: |
          docker run --rm ghcr.io/${{ github.repository }}:${{ matrix.tag }} \
            python3 -c "${{ matrix.import_cmd }}"
